[build]
  base = "backend"
  command = "mkdir -p public && echo '<!DOCTYPE html><html><body><h1>Backend API</h1></body></html>' > public/index.html && npm install"
  publish = "public"

[functions]
  directory = "src"
  node_bundler = "esbuild"
  included_files = ["src/**/*"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 