[build]
  base = "backend"
  command = "mkdir -p public && echo '<!DOCTYPE html><html><body><h1>Backend API</h1></body></html>' > public/index.html && npm install"
  publish = "public"

[functions]
  directory = "src"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:5173"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 