[build]
  base = "backend"
  command = "mkdir -p public && echo '<!DOCTYPE html><html><body><h1>Backend API</h1></body></html>' > public/index.html && npm install"
  publish = "public"

[functions]
  directory = "src"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 