[build]
  base = "backend"
  command = "npm install"
  publish = "public"

[functions]
  directory = "src"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200 