[build]
  base = "."
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["phone-numbers.xlsx"]

[build.environment]
  NODE_VERSION = "18" 